#!/bin/bash

function rebuild {
  Rscript -e "rmarkdown::render('$1.Rmd')"
#  cp $1.Rmd ../inst/doc/
#  mv $1.html ../inst/doc/
}

### Introducing Rfiglet
rebuild Rfiglet

### Figlet Fonts
Rscript -e "library(Rfiglet);Rfiglet:::fill_font_vignette()"
rebuild figlet_fonts

